name: Security Scans

on: [pull_request, push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gitleaks Secrets Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git -v

      - name: Install dependencies for scanners
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq

      - name: Tr ivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: 0

      - name: Checkov IaC Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: true

      - name: Install Conftest
        run: |
          VERSION=0.52.0
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v${VERSION}/conftest_${VERSION}_Linux_x86_64.tar.gz
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Conftest OPA Policies
        run: |
          if ls **/tfplan.json 1> /dev/null 2>&1; then
            conftest test --input terraform **/tfplan.json -p policy/opa || true
          else
            echo "No tfplan.json found; skipping conftest"
          fi

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/semgrep.yml
          generateSarif: true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
